TestCases

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,33 +1,287 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine. 
-# See: https://circleci.com/docs/2.0/configuration-reference
+# This code is licensed from CircleCI to the user under the MIT license.
+# See here for details: https://circleci.com/developer/orbs/licensing
 version: 2.1
-
-jobs:
-  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
-  build-and-test:  
-    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
-    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
-    # Be sure to update the Docker image tag below to openjdk version of your application.
-    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/openjdk
-    docker:
-      - image: cimg/openjdk:16.0
+description: |
+  Easily deploy applications to AWS CodeDeploy on CircleCI with the aws-code-deploy orb
+display:
+  home_url: https://aws.amazon.com/codedeploy/
+  source_url: https://github.com/CircleCI-Public/aws-code-deploy-orb
+orbs:
+  aws-cli: circleci/aws-cli@0.1
+commands:
+  create-application:
+    description: |
+      Creates an application.
+    parameters:
+      application-name:
+        description: The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account.
+        type: string
+      arguments:
+        default: ""
+        description: If you wish to pass any additional arguments to the aws deploy command
+        type: string
     steps:
-      # Checkout the code as the first step.
-      - checkout
-      # Use mvn clean and package as the standard maven build phase
       - run:
-          name: Build
-          command: mvn -B -DskipTests clean package
-      # Then run your tests!
+          command: |
+            set +e
+            aws deploy get-application --application-name << parameters.application-name >><<# parameters.arguments >> << parameters.arguments >><</parameters.arguments >>
+            if [ $? -ne 0 ]; then
+              set -e
+              echo "No application named << parameters.application-name >> found. Trying to create a new one"
+              aws deploy create-application --application-name << parameters.application-name >><<# parameters.arguments >> << parameters.arguments >><</parameters.arguments >>
+            else
+              set -e
+              echo "Application named << parameters.application-name >> already exists. Skipping creation."
+            fi
+          name: ensure-application-created
+  create-deployment-group:
+    description: |
+      Creates a deployment group to which application revisions are deployed.
+    parameters:
+      application-name:
+        description: The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account.
+        type: string
+      arguments:
+        default: ""
+        description: If you wish to pass any additional arguments to the create-deployment-group command
+        type: string
+      deployment-config:
+        default: CodeDeployDefault.OneAtATime
+        description: Predefined deployment configuration name.
+        type: string
+      deployment-group:
+        description: The name of a new deployment group for the specified application.
+        type: string
+      get-deployment-group-arguments:
+        default: ""
+        description: If you wish to pass any additional arguments to the get-deployment-group command
+        type: string
+      service-role-arn:
+        description: The service role for a deployment group.
+        type: string
+    steps:
       - run:
-          name: Test
-          command: mvn test
+          command: |
+            set +e
+            aws deploy get-deployment-group \
+              --application-name << parameters.application-name >> \
+              --deployment-group-name << parameters.deployment-group >><<# parameters.get-deployment-group-arguments >> << parameters.get-deployment-group-arguments >><</parameters.get-deployment-group-arguments >>
 
-workflows:
-  # Below is the definition of your workflow.
-  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
-  # CircleCI will run this workflow on every commit.
-  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
-  sample: 
-    jobs:
-      - build-and-test
+            if [ $? -ne 0 ]; then
+              set -e
+              echo "No deployment group named << parameters.deployment-group >> found. Trying to create a new one"
+              aws deploy create-deployment-group \
+                --application-name << parameters.application-name >> \
+                --deployment-group-name << parameters.deployment-group >> \
+                --deployment-config-name << parameters.deployment-config >> \
+                --service-role-arn << parameters.service-role-arn >><<# parameters.arguments >> << parameters.arguments >><</parameters.arguments >>
+            else
+              set -e
+              echo "Deployment group named << parameters.deployment-group >> already exists. Skipping creation."
+            fi
+          name: ensure-deployment-created
+  deploy-bundle:
+    description: |
+      Deploy from a bundle and wait until the deployment has successfully completed.
+    parameters:
+      application-name:
+        description: The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account.
+        type: string
+      bundle-bucket:
+        description: The s3 bucket where an application revision will be stored
+        type: string
+      bundle-key:
+        description: A key under the s3 bucket where an application revision will be stored
+        type: string
+      bundle-type:
+        default: zip
+        description: The file type used for an application revision bundle. Currently defaults to 'zip'
+        type: string
+      deploy-bundle-arguments:
+        default: ""
+        description: If you wish to pass any additional arguments to the aws create-deployment command
+        type: string
+      deployment-config:
+        default: CodeDeployDefault.OneAtATime
+        description: Predefined deployment configuration name.
+        type: string
+      deployment-group:
+        description: The name of a new deployment group for the specified application.
+        type: string
+      get-deployment-group-arguments:
+        default: ""
+        description: If you wish to pass any additional arguments to the get-deployment-group command
+        type: string
+    steps:
+      - run:
+          command: |
+            ID=$(aws deploy create-deployment \
+                    --application-name << parameters.application-name >> \
+                    --deployment-group-name << parameters.deployment-group >> \
+                    --deployment-config-name << parameters.deployment-config >> \
+                    --s3-location bucket=<< parameters.bundle-bucket >>,bundleType=<< parameters.bundle-type >>,key=<< parameters.bundle-key >>.<< parameters.bundle-type >> \
+                    --output text \
+                    --query '[deploymentId]'<<# parameters.deploy-bundle-arguments >> << parameters.deploy-bundle-arguments >><</parameters.deploy-bundle-arguments >>)
+            STATUS=$(aws deploy get-deployment \
+                      --deployment-id $ID \
+                      --output text \
+                      --query '[deploymentInfo.status]'<<# parameters.get-deployment-group-arguments >> << parameters.get-deployment-group-arguments >><</parameters.get-deployment-group-arguments >>)
+            while [[ $STATUS == "Created" || $STATUS == "InProgress" || $STATUS == "Pending" || $STATUS == "Queued" || $STATUS == "Ready" ]]; do
+              echo "Status: $STATUS..."
+              STATUS=$(aws deploy get-deployment \
+                        --deployment-id $ID \
+                        --output text \
+                        --query '[deploymentInfo.status]'<<# parameters.get-deployment-group-arguments >> << parameters.get-deployment-group-arguments >><</parameters.get-deployment-group-arguments >>)
+              sleep 5
+            done
+            if [[ $STATUS == "Succeeded" ]]; then
+              EXITCODE=0
+              echo "Deployment finished."
+            else
+              EXITCODE=1
+              echo "Deployment failed!"
+            fi
+            aws deploy get-deployment --deployment-id $ID<<# parameters.get-deployment-group-arguments >> << parameters.get-deployment-group-arguments >><</parameters.get-deployment-group-arguments >>
+            exit $EXITCODE
+          name: deploy-bundle
+  push-bundle:
+    description: |
+      Bundles and uploads to Amazon Simple Storage Service (Amazon S3) an application revision
+    parameters:
+      application-name:
+        description: The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account.
+        type: string
+      arguments:
+        default: ""
+        description: If you wish to pass any additional arguments to the aws deploy command
+        type: string
+      bundle-bucket:
+        description: The s3 bucket where an application revision will be stored
+        type: string
+      bundle-key:
+        description: A key under the s3 bucket where an application revision will be stored
+        type: string
+      bundle-source:
+        default: .
+        description: The directory relative to your project to package up into an application revision.
+        type: string
+      bundle-type:
+        default: zip
+        description: The file type used for an application revision bundle. Currently defaults to 'zip'
+        type: string
+    steps:
+      - run:
+          command: |
+            aws deploy push \
+              --application-name << parameters.application-name >> \
+              --source << parameters.bundle-source >> \
+              --s3-location s3://<< parameters.bundle-bucket >>/<< parameters.bundle-key >>.<< parameters.bundle-type >><<# parameters.arguments >> << parameters.arguments >><</parameters.arguments >>
+          name: push-bundle
+jobs:
+  deploy:
+    description: Ensures an application and deployment group exist then proceeds to bundle and upload an application revision to S3. Once uploaded this job will finally create a deployment based on that revision.
+    executor: aws-cli/default
+    parameters:
+      application-name:
+        description: The name of an AWS CodeDeploy application associated with the applicable IAM user or AWS account.
+        type: string
+      arguments:
+        default: ""
+        description: If you wish to pass any additional arguments to the aws deploy command
+        type: string
+      bundle-bucket:
+        description: The s3 bucket where an application revision will be stored
+        type: string
+      bundle-key:
+        description: A key under the s3 bucket where an application revision will be stored
+        type: string
+      bundle-source:
+        default: .
+        description: The directory relative to your project to package up into an application revision.
+        type: string
+      bundle-type:
+        default: zip
+        description: The file type used for an application revision bundle. Currently defaults to 'zip'
+        type: string
+      deploy-bundle-arguments:
+        default: ""
+        description: If you wish to pass any additional arguments to the deploy-bundle command
+        type: string
+      deployment-config:
+        default: CodeDeployDefault.OneAtATime
+        description: Predefined deployment configuration name.
+        type: string
+      deployment-group:
+        description: The name of a new deployment group for the specified application.
+        type: string
+      get-deployment-group-arguments:
+        default: ""
+        description: If you wish to pass any additional arguments to the get-deployment-group command
+        type: string
+      service-role-arn:
+        description: The service role for a deployment group.
+        type: string
+    steps:
+      - checkout
+      - aws-cli/setup
+      - create-application:
+          application-name: << parameters.application-name >>
+          arguments: << parameters.arguments >>
+      - create-deployment-group:
+          application-name: << parameters.application-name >>
+          arguments: << parameters.arguments >>
+          deployment-config: << parameters.deployment-config >>
+          deployment-group: << parameters.deployment-group >>
+          get-deployment-group-arguments: << parameters.get-deployment-group-arguments >>
+          service-role-arn: << parameters.service-role-arn >>
+      - push-bundle:
+          application-name: << parameters.application-name >>
+          arguments: << parameters.arguments >>
+          bundle-bucket: << parameters.bundle-bucket >>
+          bundle-key: << parameters.bundle-key >>
+          bundle-source: << parameters.bundle-source >>
+          bundle-type: << parameters.bundle-type >>
+      - deploy-bundle:
+          application-name: << parameters.application-name >>
+          bundle-bucket: << parameters.bundle-bucket >>
+          bundle-key: << parameters.bundle-key >>
+          bundle-type: << parameters.bundle-type >>
+          deploy-bundle-arguments: << parameters.deploy-bundle-arguments >>
+          deployment-config: << parameters.deployment-config >>
+          deployment-group: << parameters.deployment-group >>
+          get-deployment-group-arguments: << parameters.get-deployment-group-arguments >>
+examples:
+  deploy_application:
+    description: |
+      Deploy an application to AWS CodeDeploy
+    usage:
+      version: "2.1"
+      orbs:
+        aws-code-deploy: circleci/aws-code-deploy@x.y
+      workflows:
+        deploy_application:
+          jobs:
+            - aws-code-deploy/deploy:
+                application-name: EurekaServer
+                bundle-bucket: myApplicationS3Bucket
+                bundle-key: myS3BucketKey
+                deployment-group: myDeploymentGroup
+                service-role-arn: myDeploymentGroupRoleARN
+  override_credentials:
+    description: |
+      Deploy an application to AWS CodeDeploy with specific aws profile
+    usage:
+      version: "2.1"
+      orbs:
+        aws-code-deploy: circleci/aws-code-deploy@x.y
+      workflows:
+        deploy_application:
+          jobs:
+            - aws-code-deploy/deploy:
+                application-name: myApplication
+                arguments: --profile assume_role
+                bundle-bucket: myApplicationS3Bucket
+                bundle-key: myS3BucketKey
+                deployment-group: myDeploymentGroup
+                service-role-arn: myDeploymentGroupRoleARN
+
